USE MASTER
GO
IF exists (SELECT * FROM sysdatabases WHERE NAME='HotelReservations')
		DROP DATABASE HotelReservations
GO 

CREATE DATABASE HotelReservations
GO

USE HotelReservations
GO

CREATE TABLE RoomTypes (
RoomTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
RoomTypeName VARCHAR(75) NOT NULL,
Rate DECIMAL(6,2) NOT NULL
)

CREATE TABLE Amenities (
AmenityID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
AmenityName VARCHAR(50) NOT NULL
)

CREATE TABLE Rooms (
RoomID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
Max_Occupants TINYINT NOT NULL,
RoomNumber SMALLINT NOT NULL,
FloorNumber TINYINT NOT NULL,
RoomTypeID INT FOREIGN KEY REFERENCES RoomTypes(RoomTypeID)
)

CREATE TABLE RoomAmenities (
RoomID INT NOT NULL,
AmenityID INT NOT NULL
CONSTRAINT PK_RoomAmenities
	PRIMARY KEY(RoomID, AmenityID),
CONSTRAINT FK_Room_RoomAmenities
	FOREIGN KEY (RoomID)
	REFERENCES Rooms(RoomID),
CONSTRAINT FK_Amenity_RoomAmenities
	FOREIGN KEY (AmenityID)
	REFERENCES Amenities(AmenityID),
)

CREATE TABLE Rates (
RateID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
StartDate DATE NOT NULL,
EndDate DATE NOT NULL,
Rate_Description VARCHAR(100) NOT NULL
)

CREATE TABLE RoomTypeRates (
RoomTypeID INT NOT NULL,
RateID INT NOT NULL,
CONSTRAINT PK_RoomTypeRates
	PRIMARY KEY (RoomTypeID, RateID),
CONSTRAINT FK_RoomTypes_RoomTypeRates
	FOREIGN KEY (RoomTypeID)
	REFERENCES RoomTypes(RoomTypeID),
CONSTRAINT FK_Rates_RoomTypeRates
	FOREIGN KEY (RateID)
	REFERENCES Rates(RateID),
)

CREATE TABLE AddOns (
AddOnID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
AddOnType VARCHAR(50) NOT NULL,
AddOnPrice DECIMAL (8,2) NOT NULL
)

CREATE TABLE AddOnRates (
AddOnID INT NOT NULL,
RateID INT NOT NULL,
CONSTRAINT PK_AddOnRates
	PRIMARY KEY (AddOnID, RateID),
CONSTRAINT FK_AddOns_AddOnRates
	FOREIGN KEY (AddOnID)
	REFERENCES AddOns(AddOnID),
CONSTRAINT FK_Rates_AddOnRates
	FOREIGN KEY (RateID)
	REFERENCES Rates(RateID),
)

CREATE TABLE PromoTypes (
PromoTypeID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
PromoDescription VARCHAR(100) NOT NULL
)

CREATE TABLE Promos (
PromoID  INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
PromoTypeID INT FOREIGN KEY REFERENCES PromoTypes(PromoTypeID) NOT NULL,
StartDate DATE NOT NULL,
EndDate DATE NOT NULL,
)

CREATE TABLE Customers (
CustomerID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Email VARCHAR(50) NOT NULL,
Street1 VARCHAR(50) NOT NULL,
Street2 VARCHAR(50) NULL,
Country VARCHAR(30) NOT NULL,
Customer_State VARCHAR(30) NOT NULL,
Zip VARCHAR(5) NOT NULL
)

CREATE TABLE Reservations (
ReservationID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
CustomerID INT FOREIGN KEY REFERENCES Customers(CustomerID) NOT NULL,
StartDate DATE NOT NULL,
EndDate DATE NOT NULL,
PromoID INT FOREIGN KEY REFERENCES Promos(PromoID) NULL,
) 

CREATE TABLE CustomerGuests (
GuestID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Age TINYINT NOT NULL,
ReservationID INT FOREIGN KEY REFERENCES Reservations(ReservationID)
)

CREATE TABLE Bills (
BillID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
ReservationID INT FOREIGN KEY REFERENCES Reservations(ReservationID) NOT NULL,
Total DECIMAL(10,2) NOT NULL,
Tax DECIMAL(8,2) NOT NULL
)

CREATE TABLE Billing_Details (
Billing_DetailsID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
BillID INT FOREIGN KEY REFERENCES Bills(BillID) NOT NULL,
AddOnID INT FOREIGN KEY REFERENCES AddOns(AddOnID) NULL,
Quantity SMALLINT NULL,
UnitPrice DECIMAL(8,2) NULL
)
GO




