namespace CarDealership.Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class UpdateTables : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.CarModels", "CarMakeId", "dbo.CarMakes");
            DropForeignKey("dbo.Vehicles", "BodyStyleId", "dbo.BodyStyles");
            DropForeignKey("dbo.Vehicles", "CarModelId", "dbo.CarModels");
            DropForeignKey("dbo.Vehicles", "ExteriorColorId", "dbo.ExteriorColors");
            DropForeignKey("dbo.Vehicles", "InteriorColorId", "dbo.InteriorColors");
            DropForeignKey("dbo.Vehicles", "PromoId", "dbo.Promoes");
            DropForeignKey("dbo.Vehicles", "TransmissionId", "dbo.Transmissions");
            DropForeignKey("dbo.Vehicles", "VehicleTypeId", "dbo.VehicleTypes");
            DropForeignKey("dbo.Invoices", "CustomerId", "dbo.Customers");
            DropForeignKey("dbo.Invoices", "PurchaseTypeId", "dbo.PurchaseTypes");
            DropForeignKey("dbo.ContactRequests", "Vin", "dbo.Vehicles");
            DropForeignKey("dbo.Invoices", "Vin", "dbo.Vehicles");
            DropIndex("dbo.CarModels", new[] { "CarMakeId" });
            DropIndex("dbo.ContactRequests", new[] { "Vin" });
            DropIndex("dbo.Vehicles", new[] { "CarModelId" });
            DropIndex("dbo.Vehicles", new[] { "TransmissionId" });
            DropIndex("dbo.Vehicles", new[] { "InteriorColorId" });
            DropIndex("dbo.Vehicles", new[] { "ExteriorColorId" });
            DropIndex("dbo.Vehicles", new[] { "BodyStyleId" });
            DropIndex("dbo.Vehicles", new[] { "VehicleTypeId" });
            DropIndex("dbo.Vehicles", new[] { "PromoId" });
            DropIndex("dbo.Invoices", new[] { "PurchaseTypeId" });
            DropIndex("dbo.Invoices", new[] { "CustomerId" });
            DropIndex("dbo.Invoices", new[] { "Vin" });
            RenameColumn(table: "dbo.CarMakes", name: "UserId", newName: "User_Id");
            RenameColumn(table: "dbo.CarModels", name: "CarMakeId", newName: "CarMake_CarMakeId");
            RenameColumn(table: "dbo.CarModels", name: "UserId", newName: "User_Id");
            RenameColumn(table: "dbo.ContactRequests", name: "Vin", newName: "Vehicle_VehicleId");
            RenameColumn(table: "dbo.Vehicles", name: "BodyStyleId", newName: "BodyStyle_BodyStyleId");
            RenameColumn(table: "dbo.Vehicles", name: "CarModelId", newName: "CarModel_CarModelId");
            RenameColumn(table: "dbo.Vehicles", name: "ExteriorColorId", newName: "ExteriorColor_ExteriorColorId");
            RenameColumn(table: "dbo.Vehicles", name: "InteriorColorId", newName: "InteriorColor_InteriorColorId");
            RenameColumn(table: "dbo.Vehicles", name: "PromoId", newName: "Promo_PromoId");
            RenameColumn(table: "dbo.Vehicles", name: "TransmissionId", newName: "Transmission_TransmissionId");
            RenameColumn(table: "dbo.Vehicles", name: "VehicleTypeId", newName: "VehicleType_VehicleTypeId");
            RenameColumn(table: "dbo.Invoices", name: "CustomerId", newName: "Customer_CustomerId");
            RenameColumn(table: "dbo.Invoices", name: "PurchaseTypeId", newName: "PurchaseType_PurchaseTypeId");
            RenameColumn(table: "dbo.Invoices", name: "UserId", newName: "User_Id");
            RenameColumn(table: "dbo.Invoices", name: "Vin", newName: "Vehicle_VehicleId");
            RenameIndex(table: "dbo.CarMakes", name: "IX_UserId", newName: "IX_User_Id");
            RenameIndex(table: "dbo.CarModels", name: "IX_UserId", newName: "IX_User_Id");
            RenameIndex(table: "dbo.Invoices", name: "IX_UserId", newName: "IX_User_Id");
            DropPrimaryKey("dbo.Vehicles");
            AddColumn("dbo.Vehicles", "VehicleId", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Vehicles", "Description", c => c.String());
            AlterColumn("dbo.CarModels", "CarMake_CarMakeId", c => c.Int());
            AlterColumn("dbo.ContactRequests", "Vehicle_VehicleId", c => c.Int());
            AlterColumn("dbo.Vehicles", "Vin", c => c.String());
            AlterColumn("dbo.Vehicles", "CarModel_CarModelId", c => c.Int());
            AlterColumn("dbo.Vehicles", "Transmission_TransmissionId", c => c.Int());
            AlterColumn("dbo.Vehicles", "InteriorColor_InteriorColorId", c => c.Int());
            AlterColumn("dbo.Vehicles", "ExteriorColor_ExteriorColorId", c => c.Int());
            AlterColumn("dbo.Vehicles", "BodyStyle_BodyStyleId", c => c.Int());
            AlterColumn("dbo.Vehicles", "VehicleType_VehicleTypeId", c => c.Int());
            AlterColumn("dbo.Vehicles", "Promo_PromoId", c => c.Int());
            AlterColumn("dbo.Invoices", "PurchaseType_PurchaseTypeId", c => c.Int());
            AlterColumn("dbo.Invoices", "Customer_CustomerId", c => c.Int());
            AlterColumn("dbo.Invoices", "Vehicle_VehicleId", c => c.Int());
            AddPrimaryKey("dbo.Vehicles", "VehicleId");
            CreateIndex("dbo.CarModels", "CarMake_CarMakeId");
            CreateIndex("dbo.ContactRequests", "Vehicle_VehicleId");
            CreateIndex("dbo.Vehicles", "BodyStyle_BodyStyleId");
            CreateIndex("dbo.Vehicles", "CarModel_CarModelId");
            CreateIndex("dbo.Vehicles", "ExteriorColor_ExteriorColorId");
            CreateIndex("dbo.Vehicles", "InteriorColor_InteriorColorId");
            CreateIndex("dbo.Vehicles", "Promo_PromoId");
            CreateIndex("dbo.Vehicles", "Transmission_TransmissionId");
            CreateIndex("dbo.Vehicles", "VehicleType_VehicleTypeId");
            CreateIndex("dbo.Invoices", "Customer_CustomerId");
            CreateIndex("dbo.Invoices", "PurchaseType_PurchaseTypeId");
            CreateIndex("dbo.Invoices", "Vehicle_VehicleId");
            AddForeignKey("dbo.CarModels", "CarMake_CarMakeId", "dbo.CarMakes", "CarMakeId");
            AddForeignKey("dbo.Vehicles", "BodyStyle_BodyStyleId", "dbo.BodyStyles", "BodyStyleId");
            AddForeignKey("dbo.Vehicles", "CarModel_CarModelId", "dbo.CarModels", "CarModelId");
            AddForeignKey("dbo.Vehicles", "ExteriorColor_ExteriorColorId", "dbo.ExteriorColors", "ExteriorColorId");
            AddForeignKey("dbo.Vehicles", "InteriorColor_InteriorColorId", "dbo.InteriorColors", "InteriorColorId");
            AddForeignKey("dbo.Vehicles", "Promo_PromoId", "dbo.Promoes", "PromoId");
            AddForeignKey("dbo.Vehicles", "Transmission_TransmissionId", "dbo.Transmissions", "TransmissionId");
            AddForeignKey("dbo.Vehicles", "VehicleType_VehicleTypeId", "dbo.VehicleTypes", "VehicleTypeId");
            AddForeignKey("dbo.Invoices", "Customer_CustomerId", "dbo.Customers", "CustomerId");
            AddForeignKey("dbo.Invoices", "PurchaseType_PurchaseTypeId", "dbo.PurchaseTypes", "PurchaseTypeId");
            AddForeignKey("dbo.ContactRequests", "Vehicle_VehicleId", "dbo.Vehicles", "VehicleId");
            AddForeignKey("dbo.Invoices", "Vehicle_VehicleId", "dbo.Vehicles", "VehicleId");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Invoices", "Vehicle_VehicleId", "dbo.Vehicles");
            DropForeignKey("dbo.ContactRequests", "Vehicle_VehicleId", "dbo.Vehicles");
            DropForeignKey("dbo.Invoices", "PurchaseType_PurchaseTypeId", "dbo.PurchaseTypes");
            DropForeignKey("dbo.Invoices", "Customer_CustomerId", "dbo.Customers");
            DropForeignKey("dbo.Vehicles", "VehicleType_VehicleTypeId", "dbo.VehicleTypes");
            DropForeignKey("dbo.Vehicles", "Transmission_TransmissionId", "dbo.Transmissions");
            DropForeignKey("dbo.Vehicles", "Promo_PromoId", "dbo.Promoes");
            DropForeignKey("dbo.Vehicles", "InteriorColor_InteriorColorId", "dbo.InteriorColors");
            DropForeignKey("dbo.Vehicles", "ExteriorColor_ExteriorColorId", "dbo.ExteriorColors");
            DropForeignKey("dbo.Vehicles", "CarModel_CarModelId", "dbo.CarModels");
            DropForeignKey("dbo.Vehicles", "BodyStyle_BodyStyleId", "dbo.BodyStyles");
            DropForeignKey("dbo.CarModels", "CarMake_CarMakeId", "dbo.CarMakes");
            DropIndex("dbo.Invoices", new[] { "Vehicle_VehicleId" });
            DropIndex("dbo.Invoices", new[] { "PurchaseType_PurchaseTypeId" });
            DropIndex("dbo.Invoices", new[] { "Customer_CustomerId" });
            DropIndex("dbo.Vehicles", new[] { "VehicleType_VehicleTypeId" });
            DropIndex("dbo.Vehicles", new[] { "Transmission_TransmissionId" });
            DropIndex("dbo.Vehicles", new[] { "Promo_PromoId" });
            DropIndex("dbo.Vehicles", new[] { "InteriorColor_InteriorColorId" });
            DropIndex("dbo.Vehicles", new[] { "ExteriorColor_ExteriorColorId" });
            DropIndex("dbo.Vehicles", new[] { "CarModel_CarModelId" });
            DropIndex("dbo.Vehicles", new[] { "BodyStyle_BodyStyleId" });
            DropIndex("dbo.ContactRequests", new[] { "Vehicle_VehicleId" });
            DropIndex("dbo.CarModels", new[] { "CarMake_CarMakeId" });
            DropPrimaryKey("dbo.Vehicles");
            AlterColumn("dbo.Invoices", "Vehicle_VehicleId", c => c.String(maxLength: 128));
            AlterColumn("dbo.Invoices", "Customer_CustomerId", c => c.Int(nullable: false));
            AlterColumn("dbo.Invoices", "PurchaseType_PurchaseTypeId", c => c.Int(nullable: false));
            AlterColumn("dbo.Vehicles", "Promo_PromoId", c => c.Int(nullable: false));
            AlterColumn("dbo.Vehicles", "VehicleType_VehicleTypeId", c => c.Int(nullable: false));
            AlterColumn("dbo.Vehicles", "BodyStyle_BodyStyleId", c => c.Int(nullable: false));
            AlterColumn("dbo.Vehicles", "ExteriorColor_ExteriorColorId", c => c.Int(nullable: false));
            AlterColumn("dbo.Vehicles", "InteriorColor_InteriorColorId", c => c.Int(nullable: false));
            AlterColumn("dbo.Vehicles", "Transmission_TransmissionId", c => c.Int(nullable: false));
            AlterColumn("dbo.Vehicles", "CarModel_CarModelId", c => c.Int(nullable: false));
            AlterColumn("dbo.Vehicles", "Vin", c => c.String(nullable: false, maxLength: 128));
            AlterColumn("dbo.ContactRequests", "Vehicle_VehicleId", c => c.String(maxLength: 128));
            AlterColumn("dbo.CarModels", "CarMake_CarMakeId", c => c.Int(nullable: false));
            DropColumn("dbo.Vehicles", "Description");
            DropColumn("dbo.Vehicles", "VehicleId");
            AddPrimaryKey("dbo.Vehicles", "Vin");
            RenameIndex(table: "dbo.Invoices", name: "IX_User_Id", newName: "IX_UserId");
            RenameIndex(table: "dbo.CarModels", name: "IX_User_Id", newName: "IX_UserId");
            RenameIndex(table: "dbo.CarMakes", name: "IX_User_Id", newName: "IX_UserId");
            RenameColumn(table: "dbo.Invoices", name: "Vehicle_VehicleId", newName: "Vin");
            RenameColumn(table: "dbo.Invoices", name: "User_Id", newName: "UserId");
            RenameColumn(table: "dbo.Invoices", name: "PurchaseType_PurchaseTypeId", newName: "PurchaseTypeId");
            RenameColumn(table: "dbo.Invoices", name: "Customer_CustomerId", newName: "CustomerId");
            RenameColumn(table: "dbo.Vehicles", name: "VehicleType_VehicleTypeId", newName: "VehicleTypeId");
            RenameColumn(table: "dbo.Vehicles", name: "Transmission_TransmissionId", newName: "TransmissionId");
            RenameColumn(table: "dbo.Vehicles", name: "Promo_PromoId", newName: "PromoId");
            RenameColumn(table: "dbo.Vehicles", name: "InteriorColor_InteriorColorId", newName: "InteriorColorId");
            RenameColumn(table: "dbo.Vehicles", name: "ExteriorColor_ExteriorColorId", newName: "ExteriorColorId");
            RenameColumn(table: "dbo.Vehicles", name: "CarModel_CarModelId", newName: "CarModelId");
            RenameColumn(table: "dbo.Vehicles", name: "BodyStyle_BodyStyleId", newName: "BodyStyleId");
            RenameColumn(table: "dbo.ContactRequests", name: "Vehicle_VehicleId", newName: "Vin");
            RenameColumn(table: "dbo.CarModels", name: "User_Id", newName: "UserId");
            RenameColumn(table: "dbo.CarModels", name: "CarMake_CarMakeId", newName: "CarMakeId");
            RenameColumn(table: "dbo.CarMakes", name: "User_Id", newName: "UserId");
            CreateIndex("dbo.Invoices", "Vin");
            CreateIndex("dbo.Invoices", "CustomerId");
            CreateIndex("dbo.Invoices", "PurchaseTypeId");
            CreateIndex("dbo.Vehicles", "PromoId");
            CreateIndex("dbo.Vehicles", "VehicleTypeId");
            CreateIndex("dbo.Vehicles", "BodyStyleId");
            CreateIndex("dbo.Vehicles", "ExteriorColorId");
            CreateIndex("dbo.Vehicles", "InteriorColorId");
            CreateIndex("dbo.Vehicles", "TransmissionId");
            CreateIndex("dbo.Vehicles", "CarModelId");
            CreateIndex("dbo.ContactRequests", "Vin");
            CreateIndex("dbo.CarModels", "CarMakeId");
            AddForeignKey("dbo.Invoices", "Vin", "dbo.Vehicles", "Vin");
            AddForeignKey("dbo.ContactRequests", "Vin", "dbo.Vehicles", "Vin");
            AddForeignKey("dbo.Invoices", "PurchaseTypeId", "dbo.PurchaseTypes", "PurchaseTypeId", cascadeDelete: true);
            AddForeignKey("dbo.Invoices", "CustomerId", "dbo.Customers", "CustomerId", cascadeDelete: true);
            AddForeignKey("dbo.Vehicles", "VehicleTypeId", "dbo.VehicleTypes", "VehicleTypeId", cascadeDelete: true);
            AddForeignKey("dbo.Vehicles", "TransmissionId", "dbo.Transmissions", "TransmissionId", cascadeDelete: true);
            AddForeignKey("dbo.Vehicles", "PromoId", "dbo.Promoes", "PromoId", cascadeDelete: true);
            AddForeignKey("dbo.Vehicles", "InteriorColorId", "dbo.InteriorColors", "InteriorColorId", cascadeDelete: true);
            AddForeignKey("dbo.Vehicles", "ExteriorColorId", "dbo.ExteriorColors", "ExteriorColorId", cascadeDelete: true);
            AddForeignKey("dbo.Vehicles", "CarModelId", "dbo.CarModels", "CarModelId", cascadeDelete: true);
            AddForeignKey("dbo.Vehicles", "BodyStyleId", "dbo.BodyStyles", "BodyStyleId", cascadeDelete: true);
            AddForeignKey("dbo.CarModels", "CarMakeId", "dbo.CarMakes", "CarMakeId", cascadeDelete: true);
        }
    }
}
